### ISSUE TITLE
Library hungs when using local file.

### ISSUE THREAD

**Issue by mlino** [MKuranowski/pyroutelib3#28] opened 2022-01-18 21:39 UTC
I'm trying to use pyroutelib3 for a simple distance calculation from one point to another, but I'm behind a proxy. By now, it's not possible to open the proxy, so I tried to use a local OSM file instead to do some research.

```
from pyroutelib3 import *
router = Router("car", "D://Downloads/brazil-latest.osm.pbf", "pbf")

def rota(n1, n2):
    start = router.findNode(*n1) 
    end = router.findNode(*n2)
    status, route = router.doRoute(start, end) 

    if status == 'success':
        routeLatLons = list(map(router.nodeLatLon, route)) # Get actual route coordinates
        distancia = 0
        for i in range(0,len(routeLatLons)):
            lat1 = routeLatLons[i]
            if i != (len(routeLatLons)-1):
                lat2 = routeLatLons[i+1]
            distancia += distHaversine(lat1, lat2)
    return round(distancia,2)

test = rota((-15.8036242,-47.8694545),(-15.850941, -47.895680))
print(test)
```

I cannot get the result using the above code behind the proxy, but if I run the code outside the proxy and do not use the local file, the result comes fast.

**Comment by MKuranowski** [comment] 2022-01-18 21:47
There's no such thing as _hangs_, the code is just taking very long to do something - you have not said which part is slow.

Brazil is very big, Python's protobuf support is slow, the online version downloads smaller tiles and processes them on-demand - so a slow loading is expected in this case.

Closing as that's not a bug - that's how loading data works.

**Closed as completed by MKuranowski** 2022-01-18 21:47 UTC

**Comment by mlino** [comment] 2022-01-18 22:14
Thank you. I meant slow but used the word hangs wrongly. Sorry for that! Is there any way to set boundaries for limiting the data loading to the some kilometers of the start position?

**Comment by MKuranowski** [comment] 2022-01-18 22:20
Creating a Router from a local file constitutes loading the file as a whole, so you need a smaller source file. Either simply download a smaller dataset, or use [osmosis](https://wiki.openstreetmap.org/wiki/Osmosis).

And by the way, trimming doesn't necessarily mean trimming the data by a bounding polygon, usually removing details (like small residential roads for inter-city planning) is more successful.

**Comment by mlino** [comment] 2022-01-18 22:30
I got it. Thank you.
